pipeline:
  name: Clean
  with:
    build.output.directory: output
    resources.configuration.directory: integration_test_suite/integration_tests/src/test/resources/configuration
  jobs:
    - name: Clean
      steps:
        - name: Clean build output directory
          run: rm -Rf ${{ build.output.directory }}
        - name: Clean resources configuration directory
          run: rm -Rf ${{ resources.configuration.directory }}
