pipeline:
  name: Build all
  jobs:
    - name: Build All
    - steps:
      - name: Build Java 8
        run: ./vpw.sh pipelines/smoke-test/build-java-8.yaml
      - name: Build Java 11
        run: ./vpw.sh pipelines/smoke-test/build-java-11.yaml
      - name: Build Java 17
        run: ./vpw.sh pipelines/smoke-test/build-java-17.yaml
      - name: Build Java 21
        run: ./vpw.sh pipelines/smoke-test/build-java-21.yaml